sudo: false
language: go
go:
  - 1.9.x
  - master
before_install:
  - go get -u github.com/jteeuwen/go-bindata/...
  - go get github.com/mattn/goveralls
  - go-bindata -pkg htmlspec ./resources
script:
  - $GOPATH/bin/goveralls -service=travis-ci -race
matrix:
  allow_failures:
    - go: master
  fast_finish: true
notifications:
  email: false
